[package]
name = "primal"
version = "0.1.0"
authors = ["Karmesi <road_line@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "day2"
path = "src/day2.rs"

[dependencies]
primal = "^0.2"
